library slick_slides;

export 'src/layouts/content.dart';
export 'src/layouts/title.dart';
export 'src/layouts/person.dart';
export 'src/layouts/video.dart';
export 'src/transitions/fade.dart';
export 'src/transitions/transition.dart';
export 'src/slides/animated_code.dart';
export 'src/slides/bullets.dart';
export 'src/slides/full_screen_image.dart';
export 'src/slides/person.dart';
export 'src/slides/title.dart';
export 'src/slides/video.dart';
export 'src/widgets/bullets.dart';
export 'src/widgets/colored_code.dart';
export 'src/widgets/gradient_text.dart';
export 'src/deck/deck.dart';
export 'src/deck/theme.dart';
